export const US_STATES = [
  { value: "AL", label: "Alabama" },
  { value: "AK", label: "Alaska" },
  { value: "AZ", label: "Arizona" },
  { value: "AR", label: "Arkansas" },
  { value: "CA", label: "California" },
  { value: "CO", label: "Colorado" },
  { value: "CT", label: "Connecticut" },
  { value: "DE", label: "Delaware" },
  { value: "FL", label: "Florida" },
  { value: "GA", label: "Georgia" },
  { value: "HI", label: "Hawaii" },
  { value: "ID", label: "Idaho" },
  { value: "IL", label: "Illinois" },
  { value: "IN", label: "Indiana" },
  { value: "IA", label: "Iowa" },
  { value: "KS", label: "Kansas" },
  { value: "KY", label: "Kentucky" },
  { value: "LA", label: "Louisiana" },
  { value: "ME", label: "Maine" },
  { value: "MD", label: "Maryland" },
  { value: "MA", label: "Massachusetts" },
  { value: "MI", label: "Michigan" },
  { value: "MN", label: "Minnesota" },
  { value: "MS", label: "Mississippi" },
  { value: "MO", label: "Missouri" },
  { value: "MT", label: "Montana" },
  { value: "NE", label: "Nebraska" },
  { value: "NV", label: "Nevada" },
  { value: "NH", label: "New Hampshire" },
  { value: "NJ", label: "New Jersey" },
  { value: "NM", label: "New Mexico" },
  { value: "NY", label: "New York" },
  { value: "NC", label: "North Carolina" },
  { value: "ND", label: "North Dakota" },
  { value: "OH", label: "Ohio" },
  { value: "OK", label: "Oklahoma" },
  { value: "OR", label: "Oregon" },
  { value: "PA", label: "Pennsylvania" },
  { value: "RI", label: "Rhode Island" },
  { value: "SC", label: "South Carolina" },
  { value: "SD", label: "South Dakota" },
  { value: "TN", label: "Tennessee" },
  { value: "TX", label: "Texas" },
  { value: "UT", label: "Utah" },
  { value: "VT", label: "Vermont" },
  { value: "VA", label: "Virginia" },
  { value: "WA", label: "Washington" },
  { value: "WV", label: "West Virginia" },
  { value: "WI", label: "Wisconsin" },
  { value: "WY", label: "Wyoming" },
];

export const US_CITIES_BY_STATE: Record<string, string[]> = {
  FL: [
    "Miami",
    "Tampa",
    "Orlando",
    "Jacksonville",
    "Fort Lauderdale",
    "West Palm Beach",
    "St. Petersburg",
    "Cape Coral",
    "Port St. Lucie",
    "Tallahassee",
    "Naples",
    "Sarasota",
    "Fort Myers",
    "Gainesville",
    "Lakeland",
    "Pensacola",
    "Daytona Beach",
    "Boca Raton",
    "Melbourne",
    "Kissimmee",
    "Clearwater",
    "Pompano Beach",
    "Palm Bay",
    "Hollywood",
  ],
  CA: [
    "Los Angeles",
    "San Francisco",
    "San Diego",
    "San Jose",
    "Sacramento",
    "Fresno",
    "Oakland",
    "Long Beach",
    "Anaheim",
    "Riverside",
    "Santa Ana",
    "Irvine",
    "Stockton",
    "Bakersfield",
    "Fremont",
    "San Bernardino",
    "Modesto",
    "Oxnard",
    "Fontana",
    "Moreno Valley",
    "Santa Clarita",
    "Huntington Beach",
    "Glendale",
    "Oceanside",
  ],
  TX: [
    "Houston",
    "Dallas",
    "Austin",
    "San Antonio",
    "Fort Worth",
    "El Paso",
    "Arlington",
    "Corpus Christi",
    "Plano",
    "Lubbock",
    "Laredo",
    "Irving",
    "Garland",
    "Frisco",
    "McKinney",
    "Amarillo",
    "Grand Prairie",
    "Brownsville",
    "Killeen",
    "Pasadena",
    "McAllen",
    "Mesquite",
    "Denton",
    "Midland",
  ],
  NY: [
    "New York",
    "Buffalo",
    "Rochester",
    "Syracuse",
    "Albany",
    "Yonkers",
    "New Rochelle",
    "White Plains",
    "Utica",
    "Binghamton",
    "Schenectady",
    "Niagara Falls",
    "Troy",
    "Ithaca",
    "Poughkeepsie",
    "Jamestown",
    "Elmira",
    "Watertown",
    "Newburgh",
    "Kingston",
    "Saratoga Springs",
    "Mount Vernon",
    "Hempstead",
    "Freeport",
  ],
  IL: [
    "Chicago",
    "Aurora",
    "Naperville",
    "Joliet",
    "Rockford",
    "Springfield",
    "Peoria",
    "Elgin",
    "Waukegan",
    "Champaign",
    "Bloomington",
    "Decatur",
    "Evanston",
    "Des Plaines",
    "Berwyn",
    "Wheaton",
    "Belleville",
    "Moline",
    "Palatine",
    "Normal",
    "Schaumburg",
    "Bolingbrook",
    "Orland Park",
    "Tinley Park",
  ],
  PA: [
    "Philadelphia",
    "Pittsburgh",
    "Allentown",
    "Erie",
    "Reading",
    "Scranton",
    "Bethlehem",
    "Lancaster",
    "Harrisburg",
    "York",
    "Altoona",
    "Wilkes-Barre",
    "Chester",
    "Easton",
    "Lebanon",
    "Hazleton",
    "New Castle",
    "Johnstown",
    "McKeesport",
    "Hermitage",
    "Norristown",
    "Monroeville",
    "Levittown",
    "State College",
  ],
  OH: [
    "Columbus",
    "Cleveland",
    "Cincinnati",
    "Toledo",
    "Akron",
    "Dayton",
    "Canton",
    "Youngstown",
    "Parma",
    "Lorain",
    "Springfield",
    "Hamilton",
    "Kettering",
    "Elyria",
    "Lakewood",
    "Cuyahoga Falls",
    "Euclid",
    "Middletown",
    "Newark",
    "Mansfield",
    "Mentor",
    "Beavercreek",
    "Cleveland Heights",
    "Strongsville",
  ],
  GA: [
    "Atlanta",
    "Augusta",
    "Columbus",
    "Macon",
    "Savannah",
    "Athens",
    "Sandy Springs",
    "Roswell",
    "Albany",
    "Johns Creek",
    "Warner Robins",
    "Alpharetta",
    "Marietta",
    "Valdosta",
    "Smyrna",
    "Dunwoody",
    "Rome",
    "East Point",
    "Milton",
    "Gainesville",
    "Peachtree City",
    "Hinesville",
    "Newnan",
    "Statesboro",
  ],
  NC: [
    "Charlotte",
    "Raleigh",
    "Greensboro",
    "Durham",
    "Winston-Salem",
    "Fayetteville",
    "Cary",
    "Wilmington",
    "High Point",
    "Asheville",
    "Concord",
    "Greenville",
    "Jacksonville",
    "Chapel Hill",
    "Rocky Mount",
    "Burlington",
    "Huntersville",
    "Wilson",
    "Kannapolis",
    "Apex",
    "Hickory",
    "Gastonia",
    "Wake Forest",
    "Mooresville",
  ],
  MI: [
    "Detroit",
    "Grand Rapids",
    "Warren",
    "Sterling Heights",
    "Ann Arbor",
    "Lansing",
    "Flint",
    "Dearborn",
    "Livonia",
    "Troy",
    "Westland",
    "Farmington Hills",
    "Kalamazoo",
    "Wyoming",
    "Southfield",
    "Rochester Hills",
    "Taylor",
    "Pontiac",
    "St. Clair Shores",
    "Royal Oak",
    "Novi",
    "Dearborn Heights",
    "Battle Creek",
    "Saginaw",
  ],
  AZ: [
    "Phoenix",
    "Tucson",
    "Mesa",
    "Chandler",
    "Scottsdale",
    "Glendale",
    "Gilbert",
    "Tempe",
    "Peoria",
    "Surprise",
    "Yuma",
    "Avondale",
    "Goodyear",
    "Flagstaff",
    "Buckeye",
    "Lake Havasu City",
    "Casa Grande",
    "Sierra Vista",
    "Maricopa",
    "Oro Valley",
    "Prescott",
    "Bullhead City",
    "Prescott Valley",
    "Apache Junction",
  ],
  WA: [
    "Seattle",
    "Spokane",
    "Tacoma",
    "Vancouver",
    "Bellevue",
    "Kent",
    "Everett",
    "Renton",
    "Spokane Valley",
    "Federal Way",
    "Yakima",
    "Bellingham",
    "Kennewick",
    "Auburn",
    "Pasco",
    "Marysville",
    "Lakewood",
    "Redmond",
    "Shoreline",
    "Richland",
    "Kirkland",
    "Burien",
    "Sammamish",
    "Olympia",
  ],
  MA: [
    "Boston",
    "Worcester",
    "Springfield",
    "Cambridge",
    "Lowell",
    "Brockton",
    "New Bedford",
    "Quincy",
    "Lynn",
    "Fall River",
    "Newton",
    "Lawrence",
    "Somerville",
    "Framingham",
    "Haverhill",
    "Waltham",
    "Malden",
    "Brookline",
    "Plymouth",
    "Medford",
    "Taunton",
    "Revere",
    "Peabody",
    "Methuen",
  ],
  TN: [
    "Nashville",
    "Memphis",
    "Knoxville",
    "Chattanooga",
    "Clarksville",
    "Murfreesboro",
    "Franklin",
    "Jackson",
    "Johnson City",
    "Bartlett",
    "Hendersonville",
    "Kingsport",
    "Collierville",
    "Smyrna",
    "Cleveland",
    "Brentwood",
    "Germantown",
    "Columbia",
    "Spring Hill",
    "La Vergne",
    "Gallatin",
    "Mount Juliet",
    "Lebanon",
    "Morristown",
  ],
  VA: [
    "Virginia Beach",
    "Norfolk",
    "Chesapeake",
    "Richmond",
    "Newport News",
    "Alexandria",
    "Hampton",
    "Roanoke",
    "Portsmouth",
    "Suffolk",
    "Lynchburg",
    "Harrisonburg",
    "Leesburg",
    "Charlottesville",
    "Danville",
    "Blacksburg",
    "Manassas",
    "Petersburg",
    "Fredericksburg",
    "Winchester",
    "Salem",
    "Staunton",
    "Bristol",
    "Hopewell",
  ],
  CO: [
    "Denver",
    "Colorado Springs",
    "Aurora",
    "Fort Collins",
    "Lakewood",
    "Thornton",
    "Arvada",
    "Westminster",
    "Pueblo",
    "Centennial",
    "Boulder",
    "Greeley",
    "Longmont",
    "Loveland",
    "Grand Junction",
    "Broomfield",
    "Castle Rock",
    "Commerce City",
    "Parker",
    "Littleton",
    "Northglenn",
    "Brighton",
    "Englewood",
    "Wheat Ridge",
  ],
  MO: [
    "Kansas City",
    "St. Louis",
    "Springfield",
    "Columbia",
    "Independence",
    "Lee's Summit",
    "O'Fallon",
    "St. Joseph",
    "St. Charles",
    "St. Peters",
    "Blue Springs",
    "Florissant",
    "Joplin",
    "Chesterfield",
    "Jefferson City",
    "Cape Girardeau",
    "Wildwood",
    "University City",
    "Ballwin",
    "Raytown",
    "Liberty",
    "Wentzville",
    "Gladstone",
    "Grandview",
  ],
  AL: [
    "Birmingham",
    "Montgomery",
    "Mobile",
    "Huntsville",
    "Tuscaloosa",
    "Hoover",
    "Dothan",
    "Auburn",
    "Decatur",
    "Madison",
    "Florence",
    "Gadsden",
    "Vestavia Hills",
    "Prattville",
    "Phenix City",
    "Opelika",
    "Anniston",
    "Bessemer",
    "Homewood",
    "Northport",
    "Enterprise",
    "Prichard",
    "Selma",
    "Troy",
  ],
  AK: [
    "Anchorage",
    "Fairbanks",
    "Juneau",
    "Wasilla",
    "Sitka",
    "Ketchikan",
    "Kenai",
    "Kodiak",
    "Bethel",
    "Palmer",
    "Homer",
    "Barrow",
    "Nome",
    "Unalaska",
    "Soldotna",
    "Valdez",
    "Cordova",
    "Seward",
    "Dillingham",
    "Kotzebue",
    "Petersburg",
    "Wrangell",
    "Craig",
    "Haines",
  ],
  AR: [
    "Little Rock",
    "Fort Smith",
    "Fayetteville",
    "Jonesboro",
    "North Little Rock",
    "Conway",
    "Rogers",
    "Pine Bluff",
    "Bentonville",
    "Hot Springs",
    "Texarkana",
    "Springdale",
    "Russellville",
    "Paragould",
    "Batesville",
    "Blytheville",
    "Searcy",
    "Van Buren",
    "El Dorado",
    "Cabot",
    "Harrison",
    "Mountain Home",
    "Siloam Springs",
    "Camden",
  ],
  CT: [
    "Bridgeport",
    "New Haven",
    "Hartford",
    "Stamford",
    "Waterbury",
    "Norwalk",
    "Danbury",
    "New Britain",
    "West Hartford",
    "Greenwich",
    "Hamden",
    "Meriden",
    "Bristol",
    "Manchester",
    "West Haven",
    "Milford",
    "Middletown",
    "Norwich",
    "Shelton",
    "Torrington",
    "New London",
    "Ansonia",
    "Derby",
    "Groton",
  ],
  DE: [
    "Wilmington",
    "Dover",
    "Newark",
    "Middletown",
    "Smyrna",
    "Milford",
    "Seaford",
    "Georgetown",
    "Elsmere",
    "New Castle",
    "Laurel",
    "Harrington",
    "Camden",
    "Clayton",
    "Lewes",
    "Millsboro",
    "Rehoboth Beach",
    "Bethany Beach",
    "Dewey Beach",
    "Fenwick Island",
    "Ocean View",
    "Selbyville",
    "Bridgeville",
    "Delmar",
  ],
  HI: [
    "Honolulu",
    "Hilo",
    "Kailua",
    "Kaneohe",
    "Pearl City",
    "Waipahu",
    "Kahului",
    "Ewa Beach",
    "Mililani",
    "Kihei",
    "Makakilo",
    "Schofield Barracks",
    "Royal Kunia",
    "Wailuku",
    "Kapaa",
    "Lahaina",
    "Waimalu",
    "Waimea",
    "Kailua-Kona",
    "Kurtistown",
    "Pukalani",
    "Waipio",
    "Makawao",
    "Lihue",
  ],
  ID: [
    "Boise",
    "Nampa",
    "Meridian",
    "Idaho Falls",
    "Pocatello",
    "Caldwell",
    "Coeur d'Alene",
    "Twin Falls",
    "Lewiston",
    "Post Falls",
    "Rexburg",
    "Chubbuck",
    "Moscow",
    "Eagle",
    "Ammon",
    "Kuna",
    "Mountain Home",
    "Hayden",
    "Blackfoot",
    "Garden City",
    "Jerome",
    "Burley",
    "Sandpoint",
    "Weiser",
  ],
  IN: [
    "Indianapolis",
    "Fort Wayne",
    "Evansville",
    "South Bend",
    "Carmel",
    "Fishers",
    "Bloomington",
    "Hammond",
    "Gary",
    "Muncie",
    "Terre Haute",
    "Kokomo",
    "Anderson",
    "Noblesville",
    "Greenwood",
    "Elkhart",
    "Mishawaka",
    "Lawrence",
    "Jeffersonville",
    "Columbus",
    "Portage",
    "New Albany",
    "Richmond",
    "Westfield",
  ],
  IA: [
    "Des Moines",
    "Cedar Rapids",
    "Davenport",
    "Sioux City",
    "Iowa City",
    "Waterloo",
    "Council Bluffs",
    "Ames",
    "West Des Moines",
    "Dubuque",
    "Ankeny",
    "Urbandale",
    "Cedar Falls",
    "Marion",
    "Bettendorf",
    "Mason City",
    "Marshalltown",
    "Ottumwa",
    "Fort Dodge",
    "Burlington",
    "Muscatine",
    "Coralville",
    "Johnston",
    "Clinton",
  ],
  KS: [
    "Wichita",
    "Overland Park",
    "Kansas City",
    "Olathe",
    "Topeka",
    "Lawrence",
    "Shawnee",
    "Manhattan",
    "Lenexa",
    "Salina",
    "Hutchinson",
    "Leavenworth",
    "Leawood",
    "Dodge City",
    "Garden City",
    "Emporia",
    "Derby",
    "Prairie Village",
    "Hays",
    "Liberal",
    "Pittsburg",
    "Newton",
    "Great Bend",
    "McPherson",
  ],
  KY: [
    "Louisville",
    "Lexington",
    "Bowling Green",
    "Owensboro",
    "Covington",
    "Hopkinsville",
    "Richmond",
    "Florence",
    "Georgetown",
    "Henderson",
    "Elizabethtown",
    "Nicholasville",
    "Jeffersontown",
    "Frankfort",
    "Paducah",
    "Radcliff",
    "Ashland",
    "Madisonville",
    "Murray",
    "St. Matthews",
    "Middlesborough",
    "Danville",
    "Fort Thomas",
    "Shively",
  ],
  LA: [
    "New Orleans",
    "Baton Rouge",
    "Shreveport",
    "Lafayette",
    "Lake Charles",
    "Kenner",
    "Bossier City",
    "Monroe",
    "Alexandria",
    "Houma",
    "Marrero",
    "Central",
    "Laplace",
    "Prairieville",
    "Metairie",
    "Slidell",
    "Chalmette",
    "Harvey",
    "Ruston",
    "Sulphur",
    "Hammond",
    "Natchitoches",
    "Gretna",
    "Opelousas",
  ],
  ME: [
    "Portland",
    "Lewiston",
    "Bangor",
    "South Portland",
    "Auburn",
    "Biddeford",
    "Sanford",
    "Saco",
    "Augusta",
    "Westbrook",
    "Waterville",
    "Presque Isle",
    "Caribou",
    "Ellsworth",
    "Orono",
    "Old Orchard Beach",
    "Brewer",
    "Bath",
    "Calais",
    "Houlton",
    "Bar Harbor",
    "Rockland",
    "Gorham",
    "Scarborough",
  ],
  MD: [
    "Baltimore",
    "Frederick",
    "Rockville",
    "Gaithersburg",
    "Bowie",
    "Annapolis",
    "College Park",
    "Salisbury",
    "Laurel",
    "Greenbelt",
    "Cumberland",
    "Hagerstown",
    "Hyattsville",
    "Westminster",
    "Elkton",
    "Easton",
    "Aberdeen",
    "Takoma Park",
    "Cambridge",
    "Ocean City",
    "Bel Air",
    "Germantown",
    "Waldorf",
    "Bethesda",
  ],
  MN: [
    "Minneapolis",
    "St. Paul",
    "Rochester",
    "Duluth",
    "Bloomington",
    "Brooklyn Park",
    "Plymouth",
    "St. Cloud",
    "Eagan",
    "Woodbury",
    "Maple Grove",
    "Eden Prairie",
    "Coon Rapids",
    "Burnsville",
    "Mankato",
    "Apple Valley",
    "Edina",
    "St. Louis Park",
    "Moorhead",
    "Winona",
    "Richfield",
    "Roseville",
    "Minnetonka",
    "Blaine",
  ],
  MS: [
    "Jackson",
    "Gulfport",
    "Southaven",
    "Hattiesburg",
    "Biloxi",
    "Meridian",
    "Tupelo",
    "Greenville",
    "Olive Branch",
    "Horn Lake",
    "Clinton",
    "Madison",
    "Pearl",
    "Ridgeland",
    "Starkville",
    "Columbus",
    "Vicksburg",
    "Pascagoula",
    "Natchez",
    "Ocean Springs",
    "Laurel",
    "Gautier",
    "Long Beach",
    "Grenada",
  ],
  MT: [
    "Billings",
    "Missoula",
    "Great Falls",
    "Bozeman",
    "Butte",
    "Helena",
    "Kalispell",
    "Havre",
    "Anaconda",
    "Miles City",
    "Belgrade",
    "Livingston",
    "Laurel",
    "Whitefish",
    "Lewistown",
    "Sidney",
    "Glendive",
    "Hamilton",
    "Polson",
    "Columbia Falls",
    "Dillon",
    "Hardin",
    "Cut Bank",
    "Shelby",
  ],
  NE: [
    "Omaha",
    "Lincoln",
    "Bellevue",
    "Grand Island",
    "Kearney",
    "Fremont",
    "Hastings",
    "North Platte",
    "Norfolk",
    "Columbus",
    "Papillion",
    "La Vista",
    "Scottsbluff",
    "South Sioux City",
    "Beatrice",
    "Chalco",
    "McCook",
    "York",
    "Nebraska City",
    "Seward",
    "Blair",
    "Gering",
    "Plattsmouth",
    "Schuyler",
  ],
  NV: [
    "Las Vegas",
    "Henderson",
    "Reno",
    "North Las Vegas",
    "Sparks",
    "Carson City",
    "Fernley",
    "Elko",
    "Mesquite",
    "Boulder City",
    "Fallon",
    "Winnemucca",
    "West Wendover",
    "Ely",
    "Yerington",
    "Carlin",
    "Lovelock",
    "Wells",
    "Jackpot",
    "Pahrump",
    "Laughlin",
    "Incline Village",
    "Minden",
    "Gardnerville",
  ],
  NH: [
    "Manchester",
    "Nashua",
    "Concord",
    "Derry",
    "Rochester",
    "Dover",
    "Salem",
    "Merrimack",
    "Londonderry",
    "Hudson",
    "Keene",
    "Bedford",
    "Portsmouth",
    "Goffstown",
    "Laconia",
    "Hampton",
    "Milford",
    "Durham",
    "Exeter",
    "Hooksett",
    "Pelham",
    "Windham",
    "Hanover",
    "Claremont",
  ],
  NJ: [
    "Newark",
    "Jersey City",
    "Paterson",
    "Elizabeth",
    "Edison",
    "Woodbridge",
    "Lakewood",
    "Toms River",
    "Hamilton",
    "Trenton",
    "Clifton",
    "Camden",
    "Brick",
    "Cherry Hill",
    "Passaic",
    "Union City",
    "Bayonne",
    "East Orange",
    "Vineland",
    "New Brunswick",
    "Hoboken",
    "Perth Amboy",
    "West New York",
    "Plainfield",
  ],
  NM: [
    "Albuquerque",
    "Las Cruces",
    "Rio Rancho",
    "Santa Fe",
    "Roswell",
    "Farmington",
    "Clovis",
    "Hobbs",
    "Alamogordo",
    "Carlsbad",
    "Gallup",
    "Deming",
    "Los Lunas",
    "Chaparral",
    "Sunland Park",
    "Las Vegas",
    "Portales",
    "North Valley",
    "Artesia",
    "Silver City",
    "Bloomfield",
    "Anthony",
    "Socorro",
    "Taos",
  ],
  ND: [
    "Fargo",
    "Bismarck",
    "Grand Forks",
    "Minot",
    "West Fargo",
    "Williston",
    "Dickinson",
    "Mandan",
    "Jamestown",
    "Wahpeton",
    "Devils Lake",
    "Valley City",
    "Grafton",
    "Beulah",
    "Watford City",
    "Rugby",
    "Hazen",
    "Carrington",
    "New Town",
    "Stanley",
    "Bottineau",
    "Cavalier",
    "Park River",
    "Lisbon",
  ],
  OK: [
    "Oklahoma City",
    "Tulsa",
    "Norman",
    "Broken Arrow",
    "Lawton",
    "Edmond",
    "Moore",
    "Midwest City",
    "Enid",
    "Stillwater",
    "Muskogee",
    "Bartlesville",
    "Shawnee",
    "Owasso",
    "Ponca City",
    "Ardmore",
    "Duncan",
    "Bixby",
    "McAlester",
    "Tahlequah",
    "Yukon",
    "Sapulpa",
    "Bethany",
    "Mustang",
  ],
  OR: [
    "Portland",
    "Eugene",
    "Salem",
    "Gresham",
    "Hillsboro",
    "Bend",
    "Beaverton",
    "Medford",
    "Springfield",
    "Corvallis",
    "Albany",
    "Tigard",
    "Lake Oswego",
    "Keizer",
    "Grants Pass",
    "Oregon City",
    "McMinnville",
    "Redmond",
    "Tualatin",
    "West Linn",
    "Woodburn",
    "Forest Grove",
    "Newberg",
    "Roseburg",
  ],
  RI: [
    "Providence",
    "Warwick",
    "Cranston",
    "Pawtucket",
    "East Providence",
    "Woonsocket",
    "Newport",
    "Central Falls",
    "Westerly",
    "Cumberland",
    "North Providence",
    "South Kingstown",
    "Barrington",
    "Middletown",
    "Portsmouth",
    "Smithfield",
    "Lincoln",
    "Narragansett",
    "Tiverton",
    "Bristol",
    "Johnston",
    "North Kingstown",
    "West Warwick",
    "Burrillville",
  ],
  SC: [
    "Charleston",
    "Columbia",
    "North Charleston",
    "Mount Pleasant",
    "Rock Hill",
    "Greenville",
    "Summerville",
    "Sumter",
    "Hilton Head Island",
    "Spartanburg",
    "Florence",
    "Aiken",
    "Myrtle Beach",
    "Greer",
    "Anderson",
    "Greenwood",
    "Taylors",
    "Goose Creek",
    "Orangeburg",
    "Simpsonville",
    "Hanahan",
    "Cayce",
    "Beaufort",
    "Gaffney",
  ],
  SD: [
    "Sioux Falls",
    "Rapid City",
    "Aberdeen",
    "Brookings",
    "Watertown",
    "Mitchell",
    "Yankton",
    "Pierre",
    "Huron",
    "Vermillion",
    "Spearfish",
    "Madison",
    "Sturgis",
    "Lead",
    "Hot Springs",
    "Belle Fourche",
    "Milbank",
    "Chamberlain",
    "Mobridge",
    "Winner",
    "Sisseton",
    "Flandreau",
    "Canton",
    "Dell Rapids",
  ],
  UT: [
    "Salt Lake City",
    "West Valley City",
    "Provo",
    "West Jordan",
    "Orem",
    "Sandy",
    "Ogden",
    "St. George",
    "Layton",
    "Taylorsville",
    "South Jordan",
    "Lehi",
    "Logan",
    "Murray",
    "Draper",
    "Bountiful",
    "Riverton",
    "Roy",
    "Spanish Fork",
    "Pleasant Grove",
    "Cottonwood Heights",
    "Tooele",
    "Cedar City",
    "Midvale",
  ],
  VT: [
    "Burlington",
    "Essex",
    "South Burlington",
    "Colchester",
    "Rutland",
    "Montpelier",
    "Barre",
    "St. Albans",
    "Brattleboro",
    "Milton",
    "Hartford",
    "Williston",
    "Middlebury",
    "Bennington",
    "Shelburne",
    "Swanton",
    "St. Johnsbury",
    "Bellows Falls",
    "White River Junction",
    "Morrisville",
    "Springfield",
    "Randolph",
    "Northfield",
    "Vergennes",
  ],
  WV: [
    "Charleston",
    "Huntington",
    "Parkersburg",
    "Morgantown",
    "Wheeling",
    "Martinsburg",
    "Fairmont",
    "Beckley",
    "Clarksburg",
    "South Charleston",
    "St. Albans",
    "Vienna",
    "Cross Lanes",
    "Hurricane",
    "Bridgeport",
    "Moundsville",
    "Keyser",
    "New Martinsville",
    "Buckhannon",
    "Oak Hill",
    "Lewisburg",
    "Ripley",
    "Elkins",
    "Point Pleasant",
  ],
  WI: [
    "Milwaukee",
    "Madison",
    "Green Bay",
    "Kenosha",
    "Racine",
    "Appleton",
    "Waukesha",
    "Oshkosh",
    "Eau Claire",
    "Janesville",
    "West Allis",
    "La Crosse",
    "Sheboygan",
    "Wauwatosa",
    "Fond du Lac",
    "New Berlin",
    "Wausau",
    "Beloit",
    "Brookfield",
    "Fitchburg",
    "Oak Creek",
    "Manitowoc",
    "Stevens Point",
    "Neenah",
  ],
  WY: [
    "Cheyenne",
    "Casper",
    "Laramie",
    "Gillette",
    "Rock Springs",
    "Sheridan",
    "Green River",
    "Evanston",
    "Riverton",
    "Jackson",
    "Cody",
    "Rawlins",
    "Lander",
    "Torrington",
    "Powell",
    "Douglas",
    "Worland",
    "Buffalo",
    "Wheatland",
    "Newcastle",
    "Kemmerer",
    "Thermopolis",
    "Afton",
    "Saratoga",
  ],
};

export const getCitiesForState = (stateCode: string): string[] => {
  return US_CITIES_BY_STATE[stateCode] || [];
};
